version: "3.4"

services:
  consume:
    build:
      context: .
      target: production
      dockerfile: consumer/Dockerfile
    env_file:
      - .env
    command: ["python", "consumer_run.py"]
    volumes:
      - ./certificates:/app/certificates
    depends_on:
      - migrate
    restart: on-failure:5

  migrate:
    build:
      context: .
      target: test
      dockerfile: consumer/Dockerfile
    env_file:
      - .env
    command: python consumer/database/migrate.py
    restart: on-failure:5

  produce:
    build:
      context: .
      target: production
      dockerfile: producer/Dockerfile
    volumes:
      - ./certificates:/app/certificates
    env_file:
      - .env
    command: ["python", "producer_run.py"]
    restart: on-failure:5