version: "3.4"

services:
  consume:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: aiven
      POSTGRES_PASSWORD: aiven
      POSTGRES_DB: aiven_default
    volumes:
      - .:/app

  produce:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    volumes:
      - .:/app