version: "3.4"

services:
  consume:
    build:
      context: .
      target: local
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      POSTGRES_USER: aiven
      POSTGRES_PASSWORD: aiven
      POSTGRES_DB: aiven_default
    networks:
      - default
    volumes:
      - .:/app

  produce:
    build:
      context: .
      target: local
      dockerfile: Dockerfile
    volumes:
      - .:/app

  db:
    environment:
      POSTGRES_USER: aiven
      POSTGRES_PASSWORD: aiven
      POSTGRES_DB: aiven_default
    image: postgres:11.6-alpine
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
