version: "3.4"

services:
  consume:
    build:
      context: .
      target: production
      dockerfile: consumer/Dockerfile

  produce:
    build:
      context: .
      target: production
      dockerfile: consumer/Dockerfile
