version: "3.4"

services:
  consume:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    volumes:
      - .:/app

  produce:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    volumes:
      - .:/app