KAFKA_TOPIC = "KAFKA_TOPIC"
KAFKA_HOST = "KAFKA_HOST"
KAFKA_GROUP_ID = "metrics_consumer"
SSL_CAFILE = "certificates/ca.pem"
SSL_CERTFILE = "certificates/service.cert"
SSL_KEY = "certificates/service.key"