name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Add dummy certificates dir
      run: mkdir certificates

    - name: Build docker images
      run: docker-compose build

    - name: Build the docker-compose stack postgres
      run: docker-compose -f docker-compose.yml up -d db

    - name: PS docker containers
      run: docker ps

    - name: Run tests
      run: docker-compose -f docker-compose-ci.yml run consume pytest --cov=.

    - name: Run tests
      run: docker-compose -f docker-compose-ci.yml run produce pytest --cov=.
